### ISSUE TITLE
Character in MathML is not recognised

### ISSUE THREAD

**Issue by danieltuzes** [jgm/texmath#103] opened 2017-11-03 16:04 UTC
The character "SMALL CONTAINS AS MEMBER" is not recognized in MathML either in UTF-8 and HTML Entity (hex). It is important, because MathType produces this notation and MathJax also supports.

## Example:
This goes in:
```
In latex:
\[X \mathrel\backepsilon  x\]

In mathml:
<math display='block'>
 <mrow>
  <mi>X</mi><mo>&#x220D;</mo><mi>x</mi></mrow>
</math>
```
This comes out:
`In latex: $$X \mathrel\backepsilon  x$$ In mathml: $$X x$$`

I used Pandoc 2.0.0.1 and `pandoc -f html+tex_math_single_backslash in.html -t markdown -o out.md`. #

**Comment by wilx** [comment] 2017-11-04 00:38
So, after some looking around, I think the culprit is the `""` in `("base","")` in `Record` (that I had to reconstitute out of the separate arrays by printing the `records` in GHCi; this seems rather awkward and unmaintainable, IMHO) for that character:

```hs
Record {uchar = '\8717', commands = [("base",""),("unicode-math","\\smallni")], category = Rel, comments = "r: contains (SMALL CONTAINS AS MEMBER)"}
```

**Comment by wilx** [comment] 2017-11-04 00:44
Also, I could not find `\\smallni` anywhere but one answer on TeX.SO. Is it actually something existing? If it is not, maybe just using `\ni` for the small variant would be preferable rather than an empty string.

**Comment by jgm** [comment] 2017-11-04 04:23
We could use writeTeXWith in pandoc to turn on all the symbols defined in unicode-math.
The default tex templates require it, but not for pdflatex, so maybe it's a bad idea.

**Comment by jgm** [comment] 2017-11-04 04:33
And yes: this system for storing the data is really ugly, but it was forced on us by ghc's inability to handle source files with long lists of records without huge slowdowns.  I believe the problem is fixed in ghc 8.2, but we still need to support compilation with older versions.

**Comment by jgm** [comment] 2017-11-04 05:59
I'm going to revert the ugly cbits stuff and go back to putting this data in Haskell, even if it's slower to compile.  I've already fixed a large number of errors by doing this.

**Closed** 2017-11-04 06:01 UTC

**Comment by jgm** [comment] 2017-11-04 23:04
+++ Václav Haisman [Nov 04 17 11:21 ]:
>   There is a whole lot of generated sources already. This could be put
>   into a single .hs source that would generated all of the .c bits, so
>   that it remains maintainable.

In the end I just restored the Haskell source.  That didn't
slow things down too far (though we'll see if things change
with optimizations and profiling enabled).

And I realized there were lots of problems with that file,
which were much easier to spot in the Haskell than in the C.
